/**
 * This file defines the LLM agents for GlobeTrotter
 * This was originally generated by GitHub Copilot (Claude Haiku 4.5)
 * These are the agents
 * Attendant - primary communicator with user
 * Locator - find coordinates of location user gave
 * Researcher - Return facts of user-given location
 */

const { OpenAI } = require("openai");
const { FoundryLocalManager } = require("foundry-local-sdk");

class LLMAgent {
    constructor({ client, modelId, instructions, name }) {
        this.client = client;
        this.modelId = modelId;
        this.instructions = instructions; // prompt for agent
        this.name = name;
        this.history = []; // store conversation history
    }

    async respondTo(userPrompt) {
        const messages = [
            { role: "system", content: this.instructions },
            ...this.history,
            { role: "user", content: userPrompt },
        ];
        const response = await this.client.chat.completions.create({
            model: this.modelId,
            messages,
        });
        const assistantMessage = response.choices[0].message.content;

        this.history.push({ role: "user", content: userPrompt });
        this.history.push({ role: "assistant", content: assistantMessage });
        return { text: assistantMessage };
    }
}

let agents = {};
let initialised = false;
const modelAlias = "phi-4-mini"; // 3.86 GB download

async function initialise() {
    if (initialised) return;

    try {
        // Step 1: Set up the Foundry Local Manager
        console.log("Initialising Foundry Local Manager...");
        FoundryLocalManager.create({ appName: "GlobeTrotter" });
        const manager = FoundryLocalManager.instance;
        await manager.startWebService();

        // Step 2: Load the LLM model. Download it if not cached already
        console.log(`Loading ${modelAlias} model...`);
        const catalog = manager.catalog;
        const model = await catalog.getModel(modelAlias);
        if (!model.isCached) {
            console.log(`Downloading model: ${modelAlias}... (this may take a while)`);
            await model.download();
        }
        await model.load();

        // Step 3: Set up the OpenAI client
        const client = new OpenAI({
            baseURL: manager.urls[0] + "/v1",
            apiKey: "foundry-local",
        });

        // Step 4: Create the agents with their instructions
        agents.attendant = new LLMAgent({
            client: client,
            modelId: model.id,
            instructions: `You are an agent that only replies to a user's message if it is about the following:
            1. points of interest
            2. landmarks
            3. famous locations
            Limit your response to 250 words.
            If you do not find in the user's message 
            a point of interest, famous location, or landmark,
            then ask the user to clarify what he or she said.
            Do not answer any other message.
            Never apologise.`,
            name: "Attendant",
        });

        agents.locator = new LLMAgent({
            client: client,
            modelId: model.id,
            instructions: `You are an agent that ONLY returns geographic coordinates of points of interest. 
            If the message contains the name of a location, 
            Then ONLY return its geographic coordinates in JSON format. 
            Do not say anything else. 
            If the geographic coordinates cannot be found, then say "IDK 🫠"
            Use the following template for formatting the coordinates: 
            {"latitude": ##.######, "longitude": ##.######}`,
            name: "Locator",
        });

        agents.researcher = new LLMAgent({
            client: client,
            modelId: model.id,
            instructions: `You are a researcher for points of interest. 
            Only list 6 facts about the point of interest, landmark, or famous location. 
            Do not invent facts.`,
            name: "Researcher",
        });

        initialised = true;
        console.log("Agents initialised successfully!");
    } catch (error) {
        console.error("Error during agent initialisation:", error);
        throw error;
    }
}

async function processUserInput(userInput) {
    if (!initialised) {
        throw new Error("Agents not initialised");
    }

    try {
        // Step 1: Attendant responds to user
        const attendantResult = await agents.attendant.respondTo(userInput);
        const attendantText = attendantResult.text;

        // Step 2: Locator gets coordinates
        const locatorResult = await agents.locator.respondTo(attendantText);
        const locatorText = locatorResult.text;
        // If using Phi-4-mini, then it will always return coordinates in lat-long form.
        // Trying to have it return coordinates as long-lat is currently not possible.
        let coordinates = null;
        try {
            coordinates = JSON.parse(locatorText);
        } catch {
            coordinates = { error: locatorText };
        }

        // Step 3: Researcher gathers facts
        const researcherResult = await agents.researcher.respondTo(attendantText);
        const researcherText = researcherResult.text;

        return {
            attendant: attendantText,
            locator: locatorText,
            coordinates: coordinates,
            researcher: researcherText,
        };
    } catch (error) {
        console.error("Error processing user input:", error);
        throw error;
    }
}

module.exports = {
    initialize: initialise,
    processUserInput,
};
