/**
 * The Client-side chat interface for GlobeTrotter
 * This was originally generated by GitHub Copilot (Claude Haiku 4.5)
 * It has since been modified by me
 */

class ChatClient {
  constructor() {
    this.apiUrl = 'http://localhost:8000/api/chat';
    this.isLoading = false;
    this.setupUI();
  }

  setupUI() {
    const chatForm = document.getElementById('chatbox');
    const userInput = document.getElementById('user-input');
    const generateButton = document.getElementById('generate-response');
    const clearChatButton = document.getElementById('clear-chat');
    const starBackground = document.getElementById('star-background');

    if (chatForm) {
      // When a user submits his or her message
      chatForm.addEventListener('submit', (e) => {
        e.preventDefault();
        const message = userInput.value.trim();
        if (message) {
          this.sendMessage(message);
          userInput.value = '';
        }
      });
    }

    if (clearChatButton) clearChatButton.addEventListener('click', () => this.clearChat());
    //if (starBackground) this.createStars(starBackground);

    // Check server health on load
    this.checkServerHealth();
  }

  async checkServerHealth() {
    try {
      const response = await fetch('http://localhost:8000/api/health');
      if (!response.ok) {
        console.warn('Server health check failed');
      }
    } catch (error) {
      console.error('Cannot connect to server. Make sure server.js is running:', error);
      this.displayError('Cannot connect to server. Make sure to run: node server.js');
    }
  }

  async sendMessage(message) {
    if (this.isLoading) return;

    this.isLoading = true;
    this.displayUserMessage(message);

    try {
      const response = await fetch(this.apiUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ message }),
      });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }

      const data = await response.json();
      this.displayAgentResponses(data);

      // Update map if coordinates are available
      if (data.coordinates && data.coordinates.longitude && data.coordinates.latitude) {
        this.updateMap(data.coordinates);
        this.getWikiImage(data.coordinates);
      }
    } catch (error) {
      console.error('Failed to get response:', error);
      this.displayError(`Error: ${error.message}`);
    } finally {
      this.isLoading = false;
    }
  }

  displayUserMessage(message) {
    const LLMbox = document.getElementById('LLMbox');
    if (LLMbox) {
      const messageDiv = document.createElement('div');
      messageDiv.className = 'chat-message';
      messageDiv.style.marginTop = '10px';
      messageDiv.style.padding = '8px';
      messageDiv.style.backgroundColor = 'rgb(67, 67, 67)';
      messageDiv.style.color = 'rgb(255, 255, 255)';
      messageDiv.style.borderRadius = '4px';
      messageDiv.style.fontSize = '16px';
      messageDiv.style.whiteSpace = 'pre-wrap';
      messageDiv.innerHTML = `<strong>You:</strong> ${this.escapeHtml(message)}`;
      LLMbox.style.opacity = 1;
      // List latest message at the top of the chat box
      const lastMessage = LLMbox.getElementsByTagName("div")[0];
      if (lastMessage) LLMbox.insertBefore(messageDiv, lastMessage);
      else LLMbox.appendChild(messageDiv);
      // Auto-scroll to latest response
      messageDiv.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
    // Hide the welcome message
    const welcomeUser = document.getElementById('WelcomeUser');
    if (welcomeUser) welcomeUser.style.opacity = 0;
    // Remove the placeholder text in the chatbox
    const chatbox = document.getElementById('user-input')
    if (chatbox) chatbox.removeAttribute('placeholder');
  }

  displayAgentResponses(data) {
    const LLMbox = document.getElementById('LLMbox');
    if (!LLMbox) return;

    const responsesDiv = document.createElement('div');
    responsesDiv.className = 'chat-message';
    responsesDiv.style.marginTop = '15px';
    responsesDiv.style.padding = '10px';
    responsesDiv.style.backgroundColor = 'rgb(67, 67, 67)';
    responsesDiv.style.color = 'rgb(255, 255, 255)';
    responsesDiv.style.borderRadius = '4px';
    responsesDiv.style.fontSize = '16px';
    responsesDiv.style.whiteSpace = 'pre-wrap';

    let html = '';

    if (data.attendant) {
      html += `<div><strong>Attendant:</strong> ${this.escapeHtml(data.attendant)}</div>`;
    }

    if (data.locator) {
      //html += `<div style="margin-top: 8px;"><strong>📍 Locator:</strong> ${this.escapeHtml(data.locator)}</div>`;
      console.log(`Locator says: ${data.locator}`);
    }

    if (data.researcher) {
      html += `<div style="margin-top: 8px;"><strong>Facts:</strong><br>${this.escapeHtml(data.researcher)}</div>`;
    }

    responsesDiv.innerHTML = html;
    const userMessage = LLMbox.getElementsByTagName("div")[0];
    LLMbox.insertBefore(responsesDiv, userMessage);
    //LLMbox.appendChild(responsesDiv);

    // Auto-scroll to latest response
    responsesDiv.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
  }

  displayError(message) {
    const LLMbox = document.getElementById('LLMbox');
    if (LLMbox) {
      const errorDiv = document.createElement('div');
      errorDiv.className = 'chat-message';
      errorDiv.style.marginTop = '10px';
      errorDiv.style.padding = '8px';
      errorDiv.style.backgroundColor = 'rgb(244, 0, 0)';
      errorDiv.style.borderRadius = '4px';
      errorDiv.style.color = 'rgb(255, 255, 255)';
      errorDiv.innerHTML = `<strong>⚠️ Error:</strong> ${this.escapeHtml(message)}`;
      LLMbox.style.opacity = 1;
      LLMbox.appendChild(errorDiv);
    }
  }

  async clearChat() {
    const LLMbox = document.getElementById('LLMbox');
    console.log("Deleting chat history");
    let chatCleared = false;

    // Remove all chat-message divs from the UI
    const chatMessages = LLMbox.querySelectorAll('.chat-message');
    chatMessages.forEach(msg => msg.remove());

    // Clear chat history of LLM agents
    try {
      const response = await fetch('http://localhost:8000/api/clear-chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
      });
      if (response.ok) {
        console.log("Chat history cleared");
        chatCleared = true;
      } else {
        console.error('Failed to clear chat history on server');
      }
    } catch (error) {
      console.error('Error clearing chat history:', error);
    }
    // Hide the LLM chatbox section
    if (chatCleared) LLMbox.style.opacity = 0;
  }

  // For the MapLibre GL globe and MapTiler Map
  updateMap(coordinates) {
    // Remove the welcome message to make way for map elements
    const welcomeUser = document.getElementById('WelcomeUser');
    if (welcomeUser && welcomeUser.style.opacity == '0') welcomeUser.remove();

    const maptiler = document.getElementById('MapTiler');
    maptiler.style.opacity = 1;
    // This function will be called when the map is ready
    if (window.mapInstance) {
      try {
        window.mapInstance.flyTo({
          center: [
            coordinates.longitude,
            coordinates.latitude
          ],
          essential: true,
          zoom: 4,
        });
      } catch (error) {
        console.error('Failed to update map:', error);
      }
    }
    if (window.markerInstance) {
      try {
        window.markerInstance
          .setLngLat([coordinates.longitude, coordinates.latitude])
          .addTo(mapInstance);
      } catch (error) {
        console.error('Failed to update map marker:', error);
      }
    }
    if (window.detailedMap) {
      try {
        window.detailedMap.jumpTo({
          center: [
            coordinates.longitude,
            coordinates.latitude
          ],
          zoom: 15
        })
      } catch (error) {
        console.error('Failed to update MapTiler jump:', error);
      }
    }
  }

  escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
  }

  // This function returns an image from WikiMedia of the location
  // More info on Wikipedia API: https://www.mediawiki.org/wiki/API:Geosearch
  async getWikiImage(coordinates) {
    const baseUrl = "https://en.wikipedia.org/w/api.php";
    let wikiUrl = baseUrl;
    let params = {
      action: "query",
      list: "geosearch",
      gscoord: coordinates.latitude + "|" + coordinates.longitude,
      gsradius: 10000,
      gssort: "distance",
      gslimit: 1,
      format: "json"
    };
    let locationTitle;
    let locationPageId;
    let locationImage;

    // First, get the Wikipedia title of the location
    try {
      wikiUrl = wikiUrl + "?origin=*";
      Object.keys(params).forEach(function (key) { wikiUrl += "&" + key + "=" + params[key]; });
      let response = await fetch(wikiUrl);
      let data = await response.json();
      locationPageId = data.query.geosearch[0].pageid.toString();
      locationTitle = data.query.geosearch[0].title;
      locationTitle = locationTitle.trim().replaceAll(" ", "_");
    } catch (error) {
      console.log("Wikipedia title could not be obtained");
      console.log(error);
      return;
    }

    // Second, get the thumbnail image of the location
    params = {
      action: "query",
      titles: locationTitle,
      prop: "pageimages",
      pithumbsize: 300,
      format: "json"
    };
    wikiUrl = baseUrl + "?origin=*";
    Object.keys(params).forEach(function (key) { wikiUrl += "&" + key + "=" + params[key]; });
    try {
      let response = await fetch(wikiUrl);
      let data = await response.json();
      locationImage = data.query.pages[locationPageId].thumbnail.source;
    } catch (error) {
      console.log("Wikipedia image could not be obtained");
      console.log(error);
      return;
    }
  }

  // This function creates the starry background
  // It's unused because I dislike how it looks
  createStars(starContainer) {
    if (!starContainer) return;
    const numOfStars = 20;
    const screenWidth = window.innerWidth;
    const screenHeight = window.innerHeight;
    const excludeWidth = screenWidth * 0.35; // Exclude left 35% of screen width
    const excludeHeight = screenHeight * 0.40; // Exclude top 40% of screen height

    for (let i = 0; i < numOfStars; i++) {
      const starElement = document.createElement('div');
      starElement.className = 'star';

      // Create random position
      let posX = Math.random() * screenWidth;
      let posY = Math.random() * screenHeight;

      // Exclude top-left corner
      if (posX < excludeWidth && posY < excludeHeight) {
        // If star lands in excluded zone, place it elsewhere
        if (Math.random() > 0.5) {
          posX = excludeWidth + Math.random() * (screenWidth - excludeWidth);
        } else {
          posY = excludeHeight + Math.random() * (screenHeight - excludeHeight);
        }
      }

      starElement.style.left = posX + 'px';
      starElement.style.top = posY + 'px';
      starContainer.append(starElement);
    }
  }
}

// Initialize chat client when DOM is ready
document.addEventListener('DOMContentLoaded', () => {
  window.chatClient = new ChatClient();
});
